name: Branch Name Validation

on:
  pull_request:
    branches:
      - '**' # Trigger on all branches

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          # Get the branch name
          BRANCH_NAME=$(echo "${{ github.head_ref }}")

          # Define the regex pattern for valid branch names
          PATTERN="^(main|feature/[a-z0-9-]+|bug/[a-z0-9-]+|enhancement/[a-z0-9-]+)$"

          # Validate the branch name
          if [[ ! "$BRANCH_NAME" =~ $PATTERN ]]; then
            echo "Branch name '$BRANCH_NAME' is invalid."
            echo "Allowed patterns: main, feature/..., bug/..., enhancement/..."
            echo "Rules: Only lowercase letters, numbers, and hyphens (-) are allowed."
            exit 1
          fi

          echo "Branch name '$BRANCH_NAME' is valid."
